apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstpod-deploy
  namespace: pranjal
  labels:
    name: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: myfirstpodcontainer
        image: psrv3/batch19flaskapp
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  namespace: pranjal
  name: flask-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: frontend
